version: "2.1"

services:
    cms-db:
        image: mysql:8.0
        volumes:
            - "/data/xibo/db:/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: .env
        restart: always
    cms-xmr:
        image: ghcr.io/xibosignage/xibo-xmr:1.0
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: .env
    cms-web:
        image: ghcr.io/xibosignage/xibo-cms:release-4.2.3
        volumes:
            - "/data/xibo/cms/custom:/var/www/cms/custom:Z"
            - "/data/xibo/backup:/var/www/backup:Z"
            - "/data/xibo/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
            - "/data/xibo/cms/library:/var/www/cms/library:Z"
            - "/data/xibo/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
            - "/data/xibo/cms/ca-certs:/var/www/cms/ca-certs:Z"
        restart: always
        environment:
            - MYSQL_HOST=cms-db
            - XMR_HOST=cms-xmr
            - CMS_USE_MEMCACHED=true
            - MEMCACHED_HOST=cms-memcached
        env_file: .env
        mem_limit: 1g
        networks:
            - home
            - xibo_default
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.xibo.rule=Host(`xibo.lab.doepkes.de`)"
            - "traefik.http.services.xibo.loadbalancer.server.port=80"
            - "traefik.http.routers.xibo.entrypoints=websecure"
            - "traefik.http.routers.xibo.tls=true"
            - "traefik.http.routers.xibo.tls.certresolver=production"
    cms-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always
        mem_limit: 100M
    cms-quickchart:
      image: ianw/quickchart
      restart: always

networks:
   home:
     external: true
   xibo_default:
     external: true
